# Supply Chain Analysis

## Project Objective

The objective of this project is to analyze supply chain data to identify business insights related to sales, revenue, inventory, suppliers, shipping, manufacturing costs, and defect rates using Python.

## Import Required Libraries

In this section, we import all the Python libraries required for data manipulation, visualization, and analysis.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = 'plotly_white'

import warnings
warnings.filterwarnings("ignore")

##  Load the Dataset

In [2]:
df = pd.read_csv("supply_chain.csv")

## Exploratory Data Analysis (EDA)

We perform an initial exploration of the dataset to understand its structure, data types, missing values, duplicates, and summary statistics.

In [3]:
df.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [4]:
df.tail()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
95,haircare,SKU95,77.903927,65,672,7386.363944,Unknown,15,14,26,...,Mumbai,18,450,26,58.890686,Pending,1.210882,Air,Route A,778.864241
96,cosmetics,SKU96,24.423131,29,324,7698.424766,Non-binary,67,2,32,...,Mumbai,28,648,28,17.803756,Pending,3.872048,Road,Route A,188.742141
97,haircare,SKU97,3.526111,56,62,4370.916580,Male,46,19,4,...,Mumbai,10,535,13,65.765156,Fail,3.376238,Road,Route A,540.132423
98,skincare,SKU98,19.754605,43,913,8525.952560,Female,53,1,27,...,Chennai,28,581,9,5.604691,Pending,2.908122,Rail,Route A,882.198864
99,haircare,SKU99,68.517833,17,627,9185.185829,Unknown,55,8,59,...,Chennai,29,921,2,38.072899,Fail,0.346027,Rail,Route B,210.743009

In [5]:
df.shape

(100, 24)

In [6]:
df.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), object(9)
memory usage: 18.9+ KB

In [8]:
df.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239830,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976920,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [9]:
df.describe(include='object')

,Product type,SKU,Customer demographics,Shipping carriers,Supplier name,Location,Inspection results,Transportation modes,Routes
count,100,100,100,100,100,100,100,100,100
unique,3,100,4,3,5,5,3,4,3
top,skincare,SKU0,Unknown,Carrier B,Supplier 1,Kolkata,Pending,Road,Route A
freq,40,1,31,43,27,25,41,29,43

In [10]:
df.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

### Relationship Between Price and Revenue Generated

In [12]:
fig = px.scatter(df,x='Price',y='Revenue generated',color='Product type',hover_data=['Number of products sold'],trendline='ols')
fig.show()

### Sales Distribution by Product Type

In [13]:
sales_data = df.groupby('Product type')['Number of products sold'].sum().reset_index()

pie_chart  = px.pie(sales_data, values = 'Number of products sold',
                    names = 'Product type',title='Sales by Product Type',
                    hover_data=['Number of products sold'],hole=0.5,
                    color_discrete_sequence=px.colors.qualitative.Pastel)

pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()

### Defect Rate Distribution by Product Type

In [14]:
defect_rate = df.groupby('Product type')['Defect rates'].sum().reset_index()

pie_chart = px.pie(defect_rate,values='Defect rates',
                   names= 'Product type',
                   title='Defect Data Rates',
                   hover_data= ['Defect rates'],hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()

### Transportation Cost Distribution by Mode

In [15]:
transportation_cost = df.groupby('Transportation modes')['Costs'].sum().reset_index()
pie_chart = px.pie(transportation_cost,values='Costs',
                   names='Transportation modes',
                   title='Cost Distribution by Transportantion Mode',
                   hover_data=['Costs'],hole=0.5,
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()

### Total Revenue by Shipping Carrier

In [16]:
total_revenue = df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig = go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                     y=total_revenue['Revenue generated']))

fig.update_layout(title='Total Revenue by Shipping Carrier',
                  xaxis_title = 'Shipping Carrier',
                  yaxis_title = 'Revenue Generated')
fig.show()

### Average Lead Time and Manufacturing Cost by Product Type

In [17]:
avg_lead_time=df.groupby('Product type')['Lead time'].mean().reset_index()
#avg_lead time
avg_manufacturing_costs = df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
result = pd.merge(avg_lead_time,avg_manufacturing_costs, on ='Product type')
result.rename(columns={'Lead time':'Average Lead Time',
                       'Manufacturing costs':'Average Manufacturing costs'},
              inplace=True)
print(result)

  Product type  Average Lead Time  Average Manufacturing costs
0    cosmetics          13.538462                    43.052740
1     haircare          18.705882                    48.457993
2     skincare          18.000000                    48.993157

In [18]:
fig = px.bar(
    result,
    x='Product type',
    y=['Average Lead Time', 'Average Manufacturing costs'],
    barmode='group',
    title='Average Lead Time and Manufacturing Cost by Product Type'
)

fig.show()

### Revenue Generated by SKU

In [19]:
revenue_chart = px.line(df,x='SKU',
                        y='Revenue generated',
                        title='Revenue Generated by SKU')
revenue_chart.show()

### Stock Level by SKU

In [20]:
stock_chart = px.line(df,x='SKU',
                      y = 'Stock levels',
                      title = 'Stock Level by SKU')
stock_chart.show()

### Order Quantity by SKU

In [21]:
order_quantity_chart = px.bar(df,x ='SKU',
                              y = 'Order quantities',
                              title = 'Order Quantity by SKU')
order_quantity_chart.show()

## Revenue Analysis by Product Type

In [26]:
import plotly.express as px

# Revenue by Product Type
revenue_by_product = (
    df.groupby("Product type", as_index=False)["Revenue generated"]
      .sum()
      .sort_values("Revenue generated", ascending=False)
)

fig = px.bar(
    revenue_by_product,
    x="Product type",
    y="Revenue generated",
    color="Revenue generated",
    color_continuous_scale="Blues",
    text_auto=".2s",
    title="Revenue Generated by Product Type",
    labels={
        "Product type": "Product Type",
        "Revenue generated": "Total Revenue"
    },
    template="plotly_white"
)

fig.update_layout(
    title_x=0.5,
    xaxis_title="Product Type",
    yaxis_title="Total Revenue",
    margin=dict(t=80)
)

fig.update_yaxes(
    range=[0, revenue_by_product["Revenue generated"].max() * 1.15]
)

fig.update_traces(textposition="outside")
fig.show()

## Cost Analysis
Now let's analyze the shipping cost of carries:

### Shipping Cost by Shipping Carrier

In [22]:
shipping_cost_chart = px.bar(df, x = 'Shipping carriers',
                            y = 'Shipping costs',
                            title='Shipping costs By SKU'                            )
shipping_cost_chart.show()

## Conclusion

This project explored various aspects of supply chain performance through data analysis and visualization. The analysis provided valuable insights into product sales, revenue generation, inventory management, shipping costs, manufacturing costs, supplier performance, and product quality.

The findings revealed differences in revenue and sales across product types, highlighted variations in shipping costs among carriers, and identified products with higher defect rates. Additionally, comparing lead time with manufacturing costs offered a better understanding of production efficiency and operational performance.

Overall, this analysis demonstrates how data-driven decision-making can help organizations optimize inventory management, improve supplier evaluation, reduce logistics costs, and enhance product quality. These insights can support businesses in building a more efficient, cost-effective, and reliable supply chain.

In [23]:
import plotly.express as px

# Revenue by Product Type
revenue_by_product = (
    df.groupby("Product type", as_index=False)["Revenue generated"]
      .sum()
      .sort_values(by="Revenue generated", ascending=False)
)

# Plotly Bar Chart
fig = px.bar(
    revenue_by_product,
    x="Product type",
    y="Revenue generated",
    color="Revenue generated",
    color_continuous_scale="Blues",
    text_auto=".2s",
    title="Revenue Generated by Product Type",
    labels={
        "Product type": "Product Type",
        "Revenue generated": "Total Revenue"
    }
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    xaxis_title="Product Type",
    yaxis_title="Total Revenue",
    font=dict(size=14),
    coloraxis_colorbar_title="Revenue"
)

fig.update_traces(
    textposition="outside",
    hovertemplate="<b>%{x}</b><br>Total Revenue: ₹%{y:,.2f}<extra></extra>"
)

fig.show()